#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using WebPortal;

namespace WebPortal	
{
	public partial class Apoint
	{
		private int _bookcode;
		public virtual int bookcode
		{
			get
			{
				return this._bookcode;
			}
			set
			{
				this._bookcode = value;
			}
		}
		
		private DateTime _entertime;
		public virtual DateTime entertime
		{
			get
			{
				return this._entertime;
			}
			set
			{
				this._entertime = value;
			}
		}
		
		private string _apnum;
		public virtual string apnum
		{
			get
			{
                return this._apnum.Trim();
			}
			set
			{
				this._apnum = value;
			}
		}
		
		private System.Nullable<System.Char> _apprectype;
		public virtual System.Nullable<System.Char> apprectype
		{
			get
			{
				return this._apprectype;
			}
			set
			{
				this._apprectype = value;
			}
		}
		
		private string _apprecno;
		public virtual string apprecno
		{
			get
			{
                return this._apprecno.Trim();
			}
			set
			{
				this._apprecno = value;
			}
		}
		
		private string _apprecsuff;
		public virtual string apprecsuff
		{
			get
			{
                return this._apprecsuff.Trim();
			}
			set
			{
				this._apprecsuff = value;
			}
		}
		
		private int? _apppatid;
		public virtual int? apppatid
		{
			get
			{
				return this._apppatid;
			}
			set
			{
				this._apppatid = value;
			}
		}
		
		private DateTime? _elapsedtime;
		public virtual DateTime? elapsedtime
		{
			get
			{
				return this._elapsedtime;
			}
			set
			{
				this._elapsedtime = value;
			}
		}
		
		private string _apstatus;
		public virtual string apstatus
		{
			get
			{
                return this._apstatus.Trim();
			}
			set
			{
				this._apstatus = value;
			}
		}
		
		private string _apnotes;
		public virtual string apnotes
		{
			get
			{
				return this._apnotes.Trim();
			}
			set
			{
				this._apnotes = value;
			}
		}
		
		private int? _espcode;
		public virtual int? espcode
		{
			get
			{
				return this._espcode;
			}
			set
			{
				this._espcode = value;
			}
		}
		
		private string _proccode;
		public virtual string proccode
		{
			get
			{
                return this._proccode.Trim();
			}
			set
			{
				this._proccode = value;
			}
		}
		
		private string _apins;
		public virtual string apins
		{
			get
			{
                return this._apins.Trim();
			}
			set
			{
				this._apins = value;
			}
		}
		
		private string _appack;
		public virtual string appack
		{
			get
			{
                return this._appack.Trim();
			}
			set
			{
				this._appack = value;
			}
		}
		
		private string _apcreateuser;
		public virtual string apcreateuser
		{
			get
			{
                return this._apcreateuser.Trim();
			}
			set
			{
				this._apcreateuser = value;
			}
		}
		
		private DateTime? _apcreatedate;
		public virtual DateTime? apcreatedate
		{
			get
			{
				return this._apcreatedate;
			}
			set
			{
				this._apcreatedate = value;
			}
		}
		
		private string _apmoduser;
		public virtual string apmoduser
		{
			get
			{
                return this._apmoduser.Trim();
			}
			set
			{
				this._apmoduser = value;
			}
		}
		
		private DateTime? _apmoddate;
		public virtual DateTime? apmoddate
		{
			get
			{
				return this._apmoddate;
			}
			set
			{
				this._apmoddate = value;
			}
		}
		
		private DAT2000 _dat2000;
		public virtual DAT2000 DAT2000
		{
			get
			{
				return this._dat2000;
			}
			set
			{
				this._dat2000 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
