#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace WebPortal	
{
	public partial class AppBook
	{
		private int _bookcode;
		public virtual int bookcode
		{
			get
			{
				return this._bookcode;
			}
			set
			{
				this._bookcode = value;
			}
		}
		
		private DateTime _datefrom;
		public virtual DateTime datefrom
		{
			get
			{
				return this._datefrom;
			}
			set
			{
				this._datefrom = value;
			}
		}
		
		private DateTime _dateto;
		public virtual DateTime dateto
		{
			get
			{
				return this._dateto;
			}
			set
			{
				this._dateto = value;
			}
		}
		
		private string _name;
		public virtual string name
		{
			get
			{
				return this._name.Trim();
			}
			set
			{
				this._name = value;
			}
		}
		
		private int? _inter;
		public virtual int? inter
		{
			get
			{
				return this._inter;
			}
			set
			{
				this._inter = value;
			}
		}
		
		private string _notes;
		public virtual string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				this._notes = value;
			}
		}
		
		private DateTime? _df1;
		public virtual DateTime? df1
		{
			get
			{
				return this._df1;
			}
			set
			{
				this._df1 = value;
			}
		}
		
		private DateTime? _dt1;
		public virtual DateTime? dt1
		{
			get
			{
				return this._dt1;
			}
			set
			{
				this._dt1 = value;
			}
		}
		
		private DateTime? _dfe1;
		public virtual DateTime? dfe1
		{
			get
			{
				return this._dfe1;
			}
			set
			{
				this._dfe1 = value;
			}
		}
		
		private DateTime? _dte1;
		public virtual DateTime? dte1
		{
			get
			{
				return this._dte1;
			}
			set
			{
				this._dte1 = value;
			}
		}
		
		private string _ne1;
		public virtual string ne1
		{
			get
			{
				return this._ne1;
			}
			set
			{
				this._ne1 = value;
			}
		}
		
		private DateTime? _df2;
		public virtual DateTime? df2
		{
			get
			{
				return this._df2;
			}
			set
			{
				this._df2 = value;
			}
		}
		
		private DateTime? _dt2;
		public virtual DateTime? dt2
		{
			get
			{
				return this._dt2;
			}
			set
			{
				this._dt2 = value;
			}
		}
		
		private DateTime? _dfe2;
		public virtual DateTime? dfe2
		{
			get
			{
				return this._dfe2;
			}
			set
			{
				this._dfe2 = value;
			}
		}
		
		private DateTime? _dte2;
		public virtual DateTime? dte2
		{
			get
			{
				return this._dte2;
			}
			set
			{
				this._dte2 = value;
			}
		}
		
		private string _ne2;
		public virtual string ne2
		{
			get
			{
				return this._ne2;
			}
			set
			{
				this._ne2 = value;
			}
		}
		
		private DateTime? _df3;
		public virtual DateTime? df3
		{
			get
			{
				return this._df3;
			}
			set
			{
				this._df3 = value;
			}
		}
		
		private DateTime? _dt3;
		public virtual DateTime? dt3
		{
			get
			{
				return this._dt3;
			}
			set
			{
				this._dt3 = value;
			}
		}
		
		private DateTime? _dfe3;
		public virtual DateTime? dfe3
		{
			get
			{
				return this._dfe3;
			}
			set
			{
				this._dfe3 = value;
			}
		}
		
		private DateTime? _dte3;
		public virtual DateTime? dte3
		{
			get
			{
				return this._dte3;
			}
			set
			{
				this._dte3 = value;
			}
		}
		
		private string _ne3;
		public virtual string ne3
		{
			get
			{
				return this._ne3;
			}
			set
			{
				this._ne3 = value;
			}
		}
		
		private DateTime? _df4;
		public virtual DateTime? df4
		{
			get
			{
				return this._df4;
			}
			set
			{
				this._df4 = value;
			}
		}
		
		private DateTime? _dt4;
		public virtual DateTime? dt4
		{
			get
			{
				return this._dt4;
			}
			set
			{
				this._dt4 = value;
			}
		}
		
		private DateTime? _dfe4;
		public virtual DateTime? dfe4
		{
			get
			{
				return this._dfe4;
			}
			set
			{
				this._dfe4 = value;
			}
		}
		
		private DateTime? _dte4;
		public virtual DateTime? dte4
		{
			get
			{
				return this._dte4;
			}
			set
			{
				this._dte4 = value;
			}
		}
		
		private string _ne4;
		public virtual string ne4
		{
			get
			{
				return this._ne4;
			}
			set
			{
				this._ne4 = value;
			}
		}
		
		private DateTime? _df5;
		public virtual DateTime? df5
		{
			get
			{
				return this._df5;
			}
			set
			{
				this._df5 = value;
			}
		}
		
		private DateTime? _dt5;
		public virtual DateTime? dt5
		{
			get
			{
				return this._dt5;
			}
			set
			{
				this._dt5 = value;
			}
		}
		
		private DateTime? _dfe5;
		public virtual DateTime? dfe5
		{
			get
			{
				return this._dfe5;
			}
			set
			{
				this._dfe5 = value;
			}
		}
		
		private DateTime? _dte5;
		public virtual DateTime? dte5
		{
			get
			{
				return this._dte5;
			}
			set
			{
				this._dte5 = value;
			}
		}
		
		private string _ne5;
		public virtual string ne5
		{
			get
			{
				return this._ne5;
			}
			set
			{
				this._ne5 = value;
			}
		}
		
		private DateTime? _df6;
		public virtual DateTime? df6
		{
			get
			{
				return this._df6;
			}
			set
			{
				this._df6 = value;
			}
		}
		
		private DateTime? _dt6;
		public virtual DateTime? dt6
		{
			get
			{
				return this._dt6;
			}
			set
			{
				this._dt6 = value;
			}
		}
		
		private DateTime? _dfe6;
		public virtual DateTime? dfe6
		{
			get
			{
				return this._dfe6;
			}
			set
			{
				this._dfe6 = value;
			}
		}
		
		private DateTime? _dte6;
		public virtual DateTime? dte6
		{
			get
			{
				return this._dte6;
			}
			set
			{
				this._dte6 = value;
			}
		}
		
		private string _ne6;
		public virtual string ne6
		{
			get
			{
				return this._ne6;
			}
			set
			{
				this._ne6 = value;
			}
		}
		
		private DateTime? _df0;
		public virtual DateTime? df0
		{
			get
			{
				return this._df0;
			}
			set
			{
				this._df0 = value;
			}
		}
		
		private DateTime? _dt0;
		public virtual DateTime? dt0
		{
			get
			{
				return this._dt0;
			}
			set
			{
				this._dt0 = value;
			}
		}
		
		private DateTime? _dfe0;
		public virtual DateTime? dfe0
		{
			get
			{
				return this._dfe0;
			}
			set
			{
				this._dfe0 = value;
			}
		}
		
		private DateTime? _dte0;
		public virtual DateTime? dte0
		{
			get
			{
				return this._dte0;
			}
			set
			{
				this._dte0 = value;
			}
		}
		
		private string _ne0;
		public virtual string ne0
		{
			get
			{
				return this._ne0;
			}
			set
			{
				this._ne0 = value;
			}
		}
		
		private int? _espcode;
		public virtual int? espcode
		{
			get
			{
				return this._espcode;
			}
			set
			{
				this._espcode = value;
			}
		}
		
		private int? _loccode;
		public virtual int? loccode
		{
			get
			{
				return this._loccode;
			}
			set
			{
				this._loccode = value;
			}
		}
		
		private string _doccode;
		public virtual string doccode
		{
			get
			{
				return this._doccode;
			}
			set
			{
				this._doccode = value;
			}
		}
		
	}
}
#pragma warning restore 1591
