#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace WebPortal	
{
	public partial class DAT0000
	{
		private string _sysprogram;
		public virtual string sysprogram
		{
			get
			{
				return this._sysprogram;
			}
			set
			{
				this._sysprogram = value;
			}
		}
		
		private string _systype;
		public virtual string systype
		{
			get
			{
				return this._systype;
			}
			set
			{
				this._systype = value;
			}
		}
		
		private byte _syscode;
		public virtual byte syscode
		{
			get
			{
				return this._syscode;
			}
			set
			{
				this._syscode = value;
			}
		}
		
		private System.Nullable<System.Char> _sysflag;
		public virtual System.Nullable<System.Char> sysflag
		{
			get
			{
				return this._sysflag;
			}
			set
			{
				this._sysflag = value;
			}
		}
		
		private string _sysvalue;
		public virtual string sysvalue
		{
			get
			{
				return this._sysvalue;
			}
			set
			{
				this._sysvalue = value;
			}
		}
		
		private string _sysdescription;
		public virtual string sysdescription
		{
			get
			{
				return this._sysdescription;
			}
			set
			{
				this._sysdescription = value;
			}
		}
		
	}
}
#pragma warning restore 1591
