#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using WebPortal;

namespace WebPortal	
{
	public partial class DAT2000
	{
		private Char _ptrectype;
		public virtual Char ptrectype
		{
			get
			{
				return this._ptrectype;
			}
			set
			{
				this._ptrectype = value;
			}
		}
		
		private string _ptrecno;
		public virtual string ptrecno
		{
			get
			{
				return this._ptrecno;
			}
			set
			{
				this._ptrecno = value;
			}
		}
		
		private string _ptrecsuffx;
		public virtual string ptrecsuffx
		{
			get
			{
				return this._ptrecsuffx;
			}
			set
			{
				this._ptrecsuffx = value;
			}
		}
		
		private string _ptlastname;
		public virtual string ptlastname
		{
			get
			{
				return this._ptlastname;
			}
			set
			{
				this._ptlastname = value;
			}
		}
		
		private string _ptfirstname;
		public virtual string ptfirstname
		{
			get
			{
				return this._ptfirstname;
			}
			set
			{
				this._ptfirstname = value;
			}
		}
		
		private string _ptinitname;
		public virtual string ptinitname
		{
			get
			{
				return this._ptinitname;
			}
			set
			{
				this._ptinitname = value;
			}
		}
		
		private string _ptsocsec;
		public virtual string ptsocsec
		{
			get
			{
				return this._ptsocsec;
			}
			set
			{
				this._ptsocsec = value;
			}
		}
		
		private System.Nullable<System.Char> _ptsocsecsufx;
		public virtual System.Nullable<System.Char> ptsocsecsufx
		{
			get
			{
				return this._ptsocsecsufx;
			}
			set
			{
				this._ptsocsecsufx = value;
			}
		}
		
		private System.Nullable<System.Char> _ptsex;
		public virtual System.Nullable<System.Char> ptsex
		{
			get
			{
				return this._ptsex;
			}
			set
			{
				this._ptsex = value;
			}
		}
		
		private System.Nullable<System.Char> _ptcivilstatus;
		public virtual System.Nullable<System.Char> ptcivilstatus
		{
			get
			{
				return this._ptcivilstatus;
			}
			set
			{
				this._ptcivilstatus = value;
			}
		}
		
		private string _ptspouselastname;
		public virtual string ptspouselastname
		{
			get
			{
				return this._ptspouselastname;
			}
			set
			{
				this._ptspouselastname = value;
			}
		}
		
		private string _ptspousefirstname;
		public virtual string ptspousefirstname
		{
			get
			{
				return this._ptspousefirstname;
			}
			set
			{
				this._ptspousefirstname = value;
			}
		}
		
		private System.Nullable<System.Char> _ptspouseinit;
		public virtual System.Nullable<System.Char> ptspouseinit
		{
			get
			{
				return this._ptspouseinit;
			}
			set
			{
				this._ptspouseinit = value;
			}
		}
		
		private string _ptmotherlastname;
		public virtual string ptmotherlastname
		{
			get
			{
				return this._ptmotherlastname;
			}
			set
			{
				this._ptmotherlastname = value;
			}
		}
		
		private string _ptmotherfirstname;
		public virtual string ptmotherfirstname
		{
			get
			{
				return this._ptmotherfirstname;
			}
			set
			{
				this._ptmotherfirstname = value;
			}
		}
		
		private System.Nullable<System.Char> _ptmotherinit;
		public virtual System.Nullable<System.Char> ptmotherinit
		{
			get
			{
				return this._ptmotherinit;
			}
			set
			{
				this._ptmotherinit = value;
			}
		}
		
		private string _ptfatherlastname;
		public virtual string ptfatherlastname
		{
			get
			{
				return this._ptfatherlastname;
			}
			set
			{
				this._ptfatherlastname = value;
			}
		}
		
		private string _ptfatherfirstname;
		public virtual string ptfatherfirstname
		{
			get
			{
				return this._ptfatherfirstname;
			}
			set
			{
				this._ptfatherfirstname = value;
			}
		}
		
		private System.Nullable<System.Char> _ptfatherinit;
		public virtual System.Nullable<System.Char> ptfatherinit
		{
			get
			{
				return this._ptfatherinit;
			}
			set
			{
				this._ptfatherinit = value;
			}
		}
		
		private DateTime? _ptbirthdate;
		public virtual DateTime? ptbirthdate
		{
			get
			{
				return this._ptbirthdate;
			}
			set
			{
				this._ptbirthdate = value;
			}
		}
		
		private DateTime? _ptenterdate;
		public virtual DateTime? ptenterdate
		{
			get
			{
				return this._ptenterdate;
			}
			set
			{
				this._ptenterdate = value;
			}
		}
		
		private DateTime? _ptbillingdate;
		public virtual DateTime? ptbillingdate
		{
			get
			{
				return this._ptbillingdate;
			}
			set
			{
				this._ptbillingdate = value;
			}
		}
		
		private System.Nullable<System.Char> _ptbillingstatus;
		public virtual System.Nullable<System.Char> ptbillingstatus
		{
			get
			{
				return this._ptbillingstatus;
			}
			set
			{
				this._ptbillingstatus = value;
			}
		}
		
		private string _ptpaddress1;
		public virtual string ptpaddress1
		{
			get
			{
				return this._ptpaddress1;
			}
			set
			{
				this._ptpaddress1 = value;
			}
		}
		
		private string _ptpaddress2;
		public virtual string ptpaddress2
		{
			get
			{
				return this._ptpaddress2;
			}
			set
			{
				this._ptpaddress2 = value;
			}
		}
		
		private string _ptpcity;
		public virtual string ptpcity
		{
			get
			{
				return this._ptpcity;
			}
			set
			{
				this._ptpcity = value;
			}
		}
		
		private string _ptpstate;
		public virtual string ptpstate
		{
			get
			{
				return this._ptpstate;
			}
			set
			{
				this._ptpstate = value;
			}
		}
		
		private string _ptpzip;
		public virtual string ptpzip
		{
			get
			{
				return this._ptpzip;
			}
			set
			{
				this._ptpzip = value;
			}
		}
		
		private string _ptraddress1;
		public virtual string ptraddress1
		{
			get
			{
				return this._ptraddress1;
			}
			set
			{
				this._ptraddress1 = value;
			}
		}
		
		private string _ptraddress2;
		public virtual string ptraddress2
		{
			get
			{
				return this._ptraddress2;
			}
			set
			{
				this._ptraddress2 = value;
			}
		}
		
		private string _ptrcity;
		public virtual string ptrcity
		{
			get
			{
				return this._ptrcity;
			}
			set
			{
				this._ptrcity = value;
			}
		}
		
		private string _ptrstate;
		public virtual string ptrstate
		{
			get
			{
				return this._ptrstate;
			}
			set
			{
				this._ptrstate = value;
			}
		}
		
		private string _ptrzip;
		public virtual string ptrzip
		{
			get
			{
				return this._ptrzip;
			}
			set
			{
				this._ptrzip = value;
			}
		}
		
		private string _pthomephone;
		public virtual string pthomephone
		{
			get
			{
				return this._pthomephone;
			}
			set
			{
				this._pthomephone = value;
			}
		}
		
		private string _ptworkphone;
		public virtual string ptworkphone
		{
			get
			{
				return this._ptworkphone;
			}
			set
			{
				this._ptworkphone = value;
			}
		}
		
		private string _ptworkext;
		public virtual string ptworkext
		{
			get
			{
				return this._ptworkext;
			}
			set
			{
				this._ptworkext = value;
			}
		}
		
		private string _ptrespphone;
		public virtual string ptrespphone
		{
			get
			{
				return this._ptrespphone;
			}
			set
			{
				this._ptrespphone = value;
			}
		}
		
		private string _ptworkplace;
		public virtual string ptworkplace
		{
			get
			{
				return this._ptworkplace;
			}
			set
			{
				this._ptworkplace = value;
			}
		}
		
		private string _ptworktitle;
		public virtual string ptworktitle
		{
			get
			{
				return this._ptworktitle;
			}
			set
			{
				this._ptworktitle = value;
			}
		}
		
		private string _ptresplastname;
		public virtual string ptresplastname
		{
			get
			{
				return this._ptresplastname;
			}
			set
			{
				this._ptresplastname = value;
			}
		}
		
		private string _ptrespfirstname;
		public virtual string ptrespfirstname
		{
			get
			{
				return this._ptrespfirstname;
			}
			set
			{
				this._ptrespfirstname = value;
			}
		}
		
		private System.Nullable<System.Char> _ptrespinit;
		public virtual System.Nullable<System.Char> ptrespinit
		{
			get
			{
				return this._ptrespinit;
			}
			set
			{
				this._ptrespinit = value;
			}
		}
		
		private System.Nullable<System.Char> _ptaccnttype;
		public virtual System.Nullable<System.Char> ptaccnttype
		{
			get
			{
				return this._ptaccnttype;
			}
			set
			{
				this._ptaccnttype = value;
			}
		}
		
		private string _ptaccntno;
		public virtual string ptaccntno
		{
			get
			{
				return this._ptaccntno;
			}
			set
			{
				this._ptaccntno = value;
			}
		}
		
		private string _ptaccntsufx;
		public virtual string ptaccntsufx
		{
			get
			{
				return this._ptaccntsufx;
			}
			set
			{
				this._ptaccntsufx = value;
			}
		}
		
		private string _ptrefering;
		public virtual string ptrefering
		{
			get
			{
				return this._ptrefering;
			}
			set
			{
				this._ptrefering = value;
			}
		}
		
		private string _ptaccntdoctor;
		public virtual string ptaccntdoctor
		{
			get
			{
				return this._ptaccntdoctor;
			}
			set
			{
				this._ptaccntdoctor = value;
			}
		}
		
		private string _ptreligion;
		public virtual string ptreligion
		{
			get
			{
				return this._ptreligion;
			}
			set
			{
				this._ptreligion = value;
			}
		}
		
		private string _ptbirthplace;
		public virtual string ptbirthplace
		{
			get
			{
				return this._ptbirthplace;
			}
			set
			{
				this._ptbirthplace = value;
			}
		}
		
		private string _ptresponsiblerelation;
		public virtual string ptresponsiblerelation
		{
			get
			{
				return this._ptresponsiblerelation;
			}
			set
			{
				this._ptresponsiblerelation = value;
			}
		}
		
		private short? _ptweight;
		public virtual short? ptweight
		{
			get
			{
				return this._ptweight;
			}
			set
			{
				this._ptweight = value;
			}
		}
		
		private string _ptautlast1;
		public virtual string ptautlast1
		{
			get
			{
				return this._ptautlast1;
			}
			set
			{
				this._ptautlast1 = value;
			}
		}
		
		private string _ptautfirst1;
		public virtual string ptautfirst1
		{
			get
			{
				return this._ptautfirst1;
			}
			set
			{
				this._ptautfirst1 = value;
			}
		}
		
		private System.Nullable<System.Char> _ptautinit1;
		public virtual System.Nullable<System.Char> ptautinit1
		{
			get
			{
				return this._ptautinit1;
			}
			set
			{
				this._ptautinit1 = value;
			}
		}
		
		private string _ptautlast2;
		public virtual string ptautlast2
		{
			get
			{
				return this._ptautlast2;
			}
			set
			{
				this._ptautlast2 = value;
			}
		}
		
		private string _ptautfirst2;
		public virtual string ptautfirst2
		{
			get
			{
				return this._ptautfirst2;
			}
			set
			{
				this._ptautfirst2 = value;
			}
		}
		
		private System.Nullable<System.Char> _ptautinit2;
		public virtual System.Nullable<System.Char> ptautinit2
		{
			get
			{
				return this._ptautinit2;
			}
			set
			{
				this._ptautinit2 = value;
			}
		}
		
		private string _ptemail;
		public virtual string ptemail
		{
			get
			{
				return this._ptemail;
			}
			set
			{
				this._ptemail = value;
			}
		}
		
		private string _ptcelphone;
		public virtual string ptcelphone
		{
			get
			{
				return this._ptcelphone;
			}
			set
			{
				this._ptcelphone = value;
			}
		}
		
		private System.Nullable<System.Char> _ptautdocmsg;
		public virtual System.Nullable<System.Char> ptautdocmsg
		{
			get
			{
				return this._ptautdocmsg;
			}
			set
			{
				this._ptautdocmsg = value;
			}
		}
		
		private System.Nullable<System.Char> _ptautpatmsg;
		public virtual System.Nullable<System.Char> ptautpatmsg
		{
			get
			{
				return this._ptautpatmsg;
			}
			set
			{
				this._ptautpatmsg = value;
			}
		}
		
		private int? _ptethnic;
		public virtual int? ptethnic
		{
			get
			{
				return this._ptethnic;
			}
			set
			{
				this._ptethnic = value;
			}
		}
		
		private int? _ptlanguage;
		public virtual int? ptlanguage
		{
			get
			{
				return this._ptlanguage;
			}
			set
			{
				this._ptlanguage = value;
			}
		}
		
		private int? _ptrace;
		public virtual int? ptrace
		{
			get
			{
				return this._ptrace;
			}
			set
			{
				this._ptrace = value;
			}
		}
		
		private int? _ptcelsup;
		public virtual int? ptcelsup
		{
			get
			{
				return this._ptcelsup;
			}
			set
			{
				this._ptcelsup = value;
			}
		}
		
		private string _ptemrmrn;
		public virtual string ptemrmrn
		{
			get
			{
				return this._ptemrmrn;
			}
			set
			{
				this._ptemrmrn = value;
			}
		}
		
		private IList<DAT8000> _dAT8000 = new List<DAT8000>();
		public virtual IList<DAT8000> DAT8000
		{
			get
			{
				return this._dAT8000;
			}
		}
		
	}
}
#pragma warning restore 1591
