#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace WebPortal	
{
	public partial class DAT3000
	{
		private string _inscode;
		public virtual string inscode
		{
			get
			{
				return this._inscode;
			}
			set
			{
				this._inscode = value;
			}
		}
		
		private string _inssinonim;
		public virtual string inssinonim
		{
			get
			{
				return this._inssinonim;
			}
			set
			{
				this._inssinonim = value;
			}
		}
		
		private string _insname;
		public virtual string insname
		{
			get
			{
				return this._insname;
			}
			set
			{
				this._insname = value;
			}
		}
		
		private string _insaddress1;
		public virtual string insaddress1
		{
			get
			{
				return this._insaddress1;
			}
			set
			{
				this._insaddress1 = value;
			}
		}
		
		private string _insaddress2;
		public virtual string insaddress2
		{
			get
			{
				return this._insaddress2;
			}
			set
			{
				this._insaddress2 = value;
			}
		}
		
		private string _inscity;
		public virtual string inscity
		{
			get
			{
				return this._inscity;
			}
			set
			{
				this._inscity = value;
			}
		}
		
		private string _insstate;
		public virtual string insstate
		{
			get
			{
				return this._insstate;
			}
			set
			{
				this._insstate = value;
			}
		}
		
		private string _inszipcode;
		public virtual string inszipcode
		{
			get
			{
				return this._inszipcode;
			}
			set
			{
				this._inszipcode = value;
			}
		}
		
		private string _insphone1;
		public virtual string insphone1
		{
			get
			{
				return this._insphone1;
			}
			set
			{
				this._insphone1 = value;
			}
		}
		
		private string _insphone2;
		public virtual string insphone2
		{
			get
			{
				return this._insphone2;
			}
			set
			{
				this._insphone2 = value;
			}
		}
		
		private string _inscontact;
		public virtual string inscontact
		{
			get
			{
				return this._inscontact;
			}
			set
			{
				this._inscontact = value;
			}
		}
		
		private System.Nullable<System.Char> _insbillingcycle;
		public virtual System.Nullable<System.Char> insbillingcycle
		{
			get
			{
				return this._insbillingcycle;
			}
			set
			{
				this._insbillingcycle = value;
			}
		}
		
		private System.Nullable<System.Char> _insprintfee;
		public virtual System.Nullable<System.Char> insprintfee
		{
			get
			{
				return this._insprintfee;
			}
			set
			{
				this._insprintfee = value;
			}
		}
		
		private System.Nullable<System.Char> _insconversion;
		public virtual System.Nullable<System.Char> insconversion
		{
			get
			{
				return this._insconversion;
			}
			set
			{
				this._insconversion = value;
			}
		}
		
		private string _insocna;
		public virtual string insocna
		{
			get
			{
				return this._insocna;
			}
			set
			{
				this._insocna = value;
			}
		}
		
		private string _insremitance;
		public virtual string insremitance
		{
			get
			{
				return this._insremitance;
			}
			set
			{
				this._insremitance = value;
			}
		}
		
		private string _inspayerid;
		public virtual string inspayerid
		{
			get
			{
				return this._inspayerid;
			}
			set
			{
				this._inspayerid = value;
			}
		}
		
		private string _insessno;
		public virtual string insessno
		{
			get
			{
				return this._insessno;
			}
			set
			{
				this._insessno = value;
			}
		}
		
		private string _inssecondaryid;
		public virtual string inssecondaryid
		{
			get
			{
				return this._inssecondaryid;
			}
			set
			{
				this._inssecondaryid = value;
			}
		}
		
		private System.Nullable<System.Char> _insbillingunits;
		public virtual System.Nullable<System.Char> insbillingunits
		{
			get
			{
				return this._insbillingunits;
			}
			set
			{
				this._insbillingunits = value;
			}
		}
		
		private string _insrenderingrefqualifier;
		public virtual string insrenderingrefqualifier
		{
			get
			{
				return this._insrenderingrefqualifier;
			}
			set
			{
				this._insrenderingrefqualifier = value;
			}
		}
		
		private string _insreferingrefqualifier;
		public virtual string insreferingrefqualifier
		{
			get
			{
				return this._insreferingrefqualifier;
			}
			set
			{
				this._insreferingrefqualifier = value;
			}
		}
		
		private string _insbillingrefqualifier;
		public virtual string insbillingrefqualifier
		{
			get
			{
				return this._insbillingrefqualifier;
			}
			set
			{
				this._insbillingrefqualifier = value;
			}
		}
		
		private System.Nullable<System.Char> _inssecondarypayer;
		public virtual System.Nullable<System.Char> inssecondarypayer
		{
			get
			{
				return this._inssecondarypayer;
			}
			set
			{
				this._inssecondarypayer = value;
			}
		}
		
		private string _insreceivercode;
		public virtual string insreceivercode
		{
			get
			{
				return this._insreceivercode;
			}
			set
			{
				this._insreceivercode = value;
			}
		}
		
		private string _insinterchangereceiverid;
		public virtual string insinterchangereceiverid
		{
			get
			{
				return this._insinterchangereceiverid;
			}
			set
			{
				this._insinterchangereceiverid = value;
			}
		}
		
		private string _insinterchangeid;
		public virtual string insinterchangeid
		{
			get
			{
				return this._insinterchangeid;
			}
			set
			{
				this._insinterchangeid = value;
			}
		}
		
		private string _inssubmitterid;
		public virtual string inssubmitterid
		{
			get
			{
				return this._inssubmitterid;
			}
			set
			{
				this._inssubmitterid = value;
			}
		}
		
		private string _inssubmittername;
		public virtual string inssubmittername
		{
			get
			{
				return this._inssubmittername;
			}
			set
			{
				this._inssubmittername = value;
			}
		}
		
		private bool? _insmedicare;
		public virtual bool? insmedicare
		{
			get
			{
				return this._insmedicare;
			}
			set
			{
				this._insmedicare = value;
			}
		}
		
		private string _inspath;
		public virtual string inspath
		{
			get
			{
				return this._inspath;
			}
			set
			{
				this._inspath = value;
			}
		}
		
		private string _inshipaafileprefix;
		public virtual string inshipaafileprefix
		{
			get
			{
				return this._inshipaafileprefix;
			}
			set
			{
				this._inshipaafileprefix = value;
			}
		}
		
		private string _inshipaafilesuffix;
		public virtual string inshipaafilesuffix
		{
			get
			{
				return this._inshipaafilesuffix;
			}
			set
			{
				this._inshipaafilesuffix = value;
			}
		}
		
		private System.Nullable<System.Char> _insprintid;
		public virtual System.Nullable<System.Char> insprintid
		{
			get
			{
				return this._insprintid;
			}
			set
			{
				this._insprintid = value;
			}
		}
		
		private string _insubfileprefix;
		public virtual string insubfileprefix
		{
			get
			{
				return this._insubfileprefix;
			}
			set
			{
				this._insubfileprefix = value;
			}
		}
		
		private string _insubfilesuffix;
		public virtual string insubfilesuffix
		{
			get
			{
				return this._insubfilesuffix;
			}
			set
			{
				this._insubfilesuffix = value;
			}
		}
		
		private string _insubpath;
		public virtual string insubpath
		{
			get
			{
				return this._insubpath;
			}
			set
			{
				this._insubpath = value;
			}
		}
		
		private string _insubrenderingrefqualifier;
		public virtual string insubrenderingrefqualifier
		{
			get
			{
				return this._insubrenderingrefqualifier;
			}
			set
			{
				this._insubrenderingrefqualifier = value;
			}
		}
		
		private string _insubreferingrefqualifier;
		public virtual string insubreferingrefqualifier
		{
			get
			{
				return this._insubreferingrefqualifier;
			}
			set
			{
				this._insubreferingrefqualifier = value;
			}
		}
		
		private string _insubbillingrefqualifier;
		public virtual string insubbillingrefqualifier
		{
			get
			{
				return this._insubbillingrefqualifier;
			}
			set
			{
				this._insubbillingrefqualifier = value;
			}
		}
		
		private string _insubsecondaryid;
		public virtual string insubsecondaryid
		{
			get
			{
				return this._insubsecondaryid;
			}
			set
			{
				this._insubsecondaryid = value;
			}
		}
		
		private string _insubreceivercode;
		public virtual string insubreceivercode
		{
			get
			{
				return this._insubreceivercode;
			}
			set
			{
				this._insubreceivercode = value;
			}
		}
		
		private string _insubinterchangereceiverid;
		public virtual string insubinterchangereceiverid
		{
			get
			{
				return this._insubinterchangereceiverid;
			}
			set
			{
				this._insubinterchangereceiverid = value;
			}
		}
		
		private string _insubinterchangeid;
		public virtual string insubinterchangeid
		{
			get
			{
				return this._insubinterchangeid;
			}
			set
			{
				this._insubinterchangeid = value;
			}
		}
		
		private string _insubsubmitterid;
		public virtual string insubsubmitterid
		{
			get
			{
				return this._insubsubmitterid;
			}
			set
			{
				this._insubsubmitterid = value;
			}
		}
		
		private string _insubsubmittername;
		public virtual string insubsubmittername
		{
			get
			{
				return this._insubsubmittername;
			}
			set
			{
				this._insubsubmittername = value;
			}
		}
		
		private System.Nullable<System.Char> _insbillingaddress;
		public virtual System.Nullable<System.Char> insbillingaddress
		{
			get
			{
				return this._insbillingaddress;
			}
			set
			{
				this._insbillingaddress = value;
			}
		}
		
		private string _insinterchangeisa07id;
		public virtual string insinterchangeisa07id
		{
			get
			{
				return this._insinterchangeisa07id;
			}
			set
			{
				this._insinterchangeisa07id = value;
			}
		}
		
		private System.Nullable<System.Char> _insaskreferring;
		public virtual System.Nullable<System.Char> insaskreferring
		{
			get
			{
				return this._insaskreferring;
			}
			set
			{
				this._insaskreferring = value;
			}
		}
		
		private System.Nullable<System.Char> _insprintreferring;
		public virtual System.Nullable<System.Char> insprintreferring
		{
			get
			{
				return this._insprintreferring;
			}
			set
			{
				this._insprintreferring = value;
			}
		}
		
		private System.Nullable<System.Char> _inscompprintfee;
		public virtual System.Nullable<System.Char> inscompprintfee
		{
			get
			{
				return this._inscompprintfee;
			}
			set
			{
				this._inscompprintfee = value;
			}
		}
		
		private string _inspaypath;
		public virtual string inspaypath
		{
			get
			{
				return this._inspaypath;
			}
			set
			{
				this._inspaypath = value;
			}
		}
		
		private System.Nullable<System.Char> _insbillproviderno;
		public virtual System.Nullable<System.Char> insbillproviderno
		{
			get
			{
				return this._insbillproviderno;
			}
			set
			{
				this._insbillproviderno = value;
			}
		}
		
		private System.Nullable<System.Char> _insbillupin;
		public virtual System.Nullable<System.Char> insbillupin
		{
			get
			{
				return this._insbillupin;
			}
			set
			{
				this._insbillupin = value;
			}
		}
		
		private decimal? _insdeductible;
		public virtual decimal? insdeductible
		{
			get
			{
				return this._insdeductible;
			}
			set
			{
				this._insdeductible = value;
			}
		}
		
		private System.Nullable<System.Char> _insaskprono;
		public virtual System.Nullable<System.Char> insaskprono
		{
			get
			{
				return this._insaskprono;
			}
			set
			{
				this._insaskprono = value;
			}
		}
		
		private System.Nullable<System.Char> _insprovesp;
		public virtual System.Nullable<System.Char> insprovesp
		{
			get
			{
				return this._insprovesp;
			}
			set
			{
				this._insprovesp = value;
			}
		}
		
		private System.Nullable<System.Char> _insprovloc;
		public virtual System.Nullable<System.Char> insprovloc
		{
			get
			{
				return this._insprovloc;
			}
			set
			{
				this._insprovloc = value;
			}
		}
		
		private System.Nullable<System.Char> _insprovdoc;
		public virtual System.Nullable<System.Char> insprovdoc
		{
			get
			{
				return this._insprovdoc;
			}
			set
			{
				this._insprovdoc = value;
			}
		}
		
		private System.Nullable<System.Char> _insinovamed;
		public virtual System.Nullable<System.Char> insinovamed
		{
			get
			{
				return this._insinovamed;
			}
			set
			{
				this._insinovamed = value;
			}
		}
		
	}
}
#pragma warning restore 1591
