#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using WebPortal;

namespace WebPortal	
{
	public partial class DAT8000
	{
		private Char _pipattype;
		public virtual Char pipattype
		{
			get
			{
				return this._pipattype;
			}
			set
			{
				this._pipattype = value;
			}
		}
		
		private string _pipatno;
		public virtual string pipatno
		{
			get
			{
				return this._pipatno.Trim();
			}
			set
			{
				this._pipatno = value;
			}
		}
		
		private string _pipatsufx;
		public virtual string pipatsufx
		{
			get
			{
                return this._pipatsufx.Trim();
			}
			set
			{
				this._pipatsufx = value;
			}
		}
		
		private byte _piorden;
		public virtual byte piorden
		{
			get
			{
				return this._piorden;
			}
			set
			{
				this._piorden = value;
			}
		}
		
		private System.Nullable<System.Char> _pitype;
		public virtual System.Nullable<System.Char> pitype
		{
			get
			{
				return this._pitype;
			}
			set
			{
				this._pitype = value;
			}
		}
		
		private string _piinscode;
		public virtual string piinscode
		{
			get
			{
                return this._piinscode.Trim();
			}
			set
			{
				this._piinscode = value;
			}
		}
		
		private string _pilastname;
		public virtual string pilastname
		{
			get
			{
                return this._pilastname.Trim();
			}
			set
			{
				this._pilastname = value;
			}
		}
		
		private string _pifirstname;
		public virtual string pifirstname
		{
			get
			{
                return this._pifirstname.Trim();
			}
			set
			{
				this._pifirstname = value;
			}
		}
		
		private string _piinitname;
		public virtual string piinitname
		{
			get
			{
                return this._piinitname.Trim();
			}
			set
			{
				this._piinitname = value;
			}
		}
		
		private System.Nullable<System.Char> _pisex;
		public virtual System.Nullable<System.Char> pisex
		{
			get
			{
				return this._pisex;
			}
			set
			{
				this._pisex = value;
			}
		}
		
		private string _pisocsec;
		public virtual string pisocsec
		{
			get
			{
                return this._pisocsec.Trim();
			}
			set
			{
				this._pisocsec = value;
			}
		}
		
		private System.Nullable<System.Char> _pisocsecsufx;
		public virtual System.Nullable<System.Char> pisocsecsufx
		{
			get
			{
				return this._pisocsecsufx;
			}
			set
			{
				this._pisocsecsufx = value;
			}
		}
		
		private string _piworkplace;
		public virtual string piworkplace
		{
			get
			{
                return this._piworkplace.Trim();
			}
			set
			{
				this._piworkplace = value;
			}
		}
		
		private DateTime? _pibirthdate;
		public virtual DateTime? pibirthdate
		{
			get
			{
				return this._pibirthdate;
			}
			set
			{
				this._pibirthdate = value;
			}
		}
		
		private string _piaddress1;
		public virtual string piaddress1
		{
			get
			{
                return this._piaddress1.Trim();
			}
			set
			{
				this._piaddress1 = value;
			}
		}
		
		private string _piaddress2;
		public virtual string piaddress2
		{
			get
			{
				return this._piaddress2.Trim();
			}
			set
			{
				this._piaddress2 = value;
			}
		}
		
		private string _picity;
		public virtual string picity
		{
			get
			{
                return this._picity.Trim();
			}
			set
			{
				this._picity = value;
			}
		}
		
		private string _pistate;
		public virtual string pistate
		{
			get
			{
                return this._pistate.Trim();
			}
			set
			{
				this._pistate = value;
			}
		}
		
		private string _pizip;
		public virtual string pizip
		{
			get
			{
                return this._pizip.Trim();
			}
			set
			{
				this._pizip = value;
			}
		}
		
		private string _piidsubscriber;
		public virtual string piidsubscriber
		{
			get
			{
                return this._piidsubscriber.Trim();
			}
			set
			{
				this._piidsubscriber = value;
			}
		}
		
		private string _piidpatient;
		public virtual string piidpatient
		{
			get
			{
                return this._piidpatient.Trim();
			}
			set
			{
				this._piidpatient = value;
			}
		}
		
		private string _pigroup;
		public virtual string pigroup
		{
			get
			{
                return this._pigroup.Trim();
			}
			set
			{
				this._pigroup = value;
			}
		}
		
		private string _picover;
		public virtual string picover
		{
			get
			{
                return this._picover.Trim();
			}
			set
			{
				this._picover = value;
			}
		}
		
		private System.Nullable<System.Char> _pirelation;
		public virtual System.Nullable<System.Char> pirelation
		{
			get
			{
				return this._pirelation;
			}
			set
			{
				this._pirelation = value;
			}
		}
		
		private DateTime? _piexpdate;
		public virtual DateTime? piexpdate
		{
			get
			{
				return this._piexpdate;
			}
			set
			{
				this._piexpdate = value;
			}
		}
		
		private DateTime? _piaccdate;
		public virtual DateTime? piaccdate
		{
			get
			{
				return this._piaccdate;
			}
			set
			{
				this._piaccdate = value;
			}
		}
		
		private System.Nullable<System.Char> _picondemp;
		public virtual System.Nullable<System.Char> picondemp
		{
			get
			{
				return this._picondemp;
			}
			set
			{
				this._picondemp = value;
			}
		}
		
		private System.Nullable<System.Char> _picondacc;
		public virtual System.Nullable<System.Char> picondacc
		{
			get
			{
				return this._picondacc;
			}
			set
			{
				this._picondacc = value;
			}
		}
		
		private string _pisubscriberlastname;
		public virtual string pisubscriberlastname
		{
			get
			{
                return this._pisubscriberlastname.Trim();
			}
			set
			{
				this._pisubscriberlastname = value;
			}
		}
		
		private string _pisubscriberfirstname;
		public virtual string pisubscriberfirstname
		{
			get
			{
                return this._pisubscriberfirstname.Trim();
			}
			set
			{
				this._pisubscriberfirstname = value;
			}
		}
		
		private System.Nullable<System.Char> _pisubscriberinit;
		public virtual System.Nullable<System.Char> pisubscriberinit
		{
			get
			{
				return this._pisubscriberinit;
			}
			set
			{
				this._pisubscriberinit = value;
			}
		}
		
		private string _picoverdesc;
		public virtual string picoverdesc
		{
			get
			{
                return this._picoverdesc.Trim();
			}
			set
			{
				this._picoverdesc = value;
			}
		}
		
		private string _pinotes;
		public virtual string pinotes
		{
			get
			{
                return this._pinotes.Trim();
			}
			set
			{
				this._pinotes = value;
			}
		}
		
		private byte? _pidisplayorder;
		public virtual byte? pidisplayorder
		{
			get
			{
				return this._pidisplayorder;
			}
			set
			{
				this._pidisplayorder = value;
			}
		}
		
		private DAT2000 _dat2000;
		public virtual DAT2000 dat2000
		{
			get
			{
				return this._dat2000;
			}
			set
			{
				this._dat2000 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
