#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace WebPortal	
{
	public partial class DAT9397F
	{
		private string _faccode;
		public virtual string faccode
		{
			get
			{
				return this._faccode;
			}
			set
			{
				this._faccode = value;
			}
		}
		
		private string _faclastname;
		public virtual string faclastname
		{
			get
			{
				return this._faclastname;
			}
			set
			{
				this._faclastname = value;
			}
		}
		
		private string _facfirstname;
		public virtual string facfirstname
		{
			get
			{
				return this._facfirstname;
			}
			set
			{
				this._facfirstname = value;
			}
		}
		
		private string _facinitname;
		public virtual string facinitname
		{
			get
			{
				return this._facinitname;
			}
			set
			{
				this._facinitname = value;
			}
		}
		
		private string _facaddress01;
		public virtual string facaddress01
		{
			get
			{
				return this._facaddress01;
			}
			set
			{
				this._facaddress01 = value;
			}
		}
		
		private string _facaddress02;
		public virtual string facaddress02
		{
			get
			{
				return this._facaddress02;
			}
			set
			{
				this._facaddress02 = value;
			}
		}
		
		private string _faccity;
		public virtual string faccity
		{
			get
			{
				return this._faccity;
			}
			set
			{
				this._faccity = value;
			}
		}
		
		private string _facstate;
		public virtual string facstate
		{
			get
			{
				return this._facstate;
			}
			set
			{
				this._facstate = value;
			}
		}
		
		private string _faczipcode;
		public virtual string faczipcode
		{
			get
			{
				return this._faczipcode;
			}
			set
			{
				this._faczipcode = value;
			}
		}
		
		private string _facsocsec;
		public virtual string facsocsec
		{
			get
			{
				return this._facsocsec;
			}
			set
			{
				this._facsocsec = value;
			}
		}
		
		private string _faclicno;
		public virtual string faclicno
		{
			get
			{
				return this._faclicno;
			}
			set
			{
				this._faclicno = value;
			}
		}
		
		private string _facupin;
		public virtual string facupin
		{
			get
			{
				return this._facupin;
			}
			set
			{
				this._facupin = value;
			}
		}
		
		private System.Nullable<System.Char> _facacceptmc;
		public virtual System.Nullable<System.Char> facacceptmc
		{
			get
			{
				return this._facacceptmc;
			}
			set
			{
				this._facacceptmc = value;
			}
		}
		
		private string _facremarks;
		public virtual string facremarks
		{
			get
			{
				return this._facremarks;
			}
			set
			{
				this._facremarks = value;
			}
		}
		
		private string _facnationalid;
		public virtual string facnationalid
		{
			get
			{
				return this._facnationalid;
			}
			set
			{
				this._facnationalid = value;
			}
		}
		
		private string _facphone;
		public virtual string facphone
		{
			get
			{
				return this._facphone;
			}
			set
			{
				this._facphone = value;
			}
		}
		
		private string _factax;
		public virtual string factax
		{
			get
			{
				return this._factax;
			}
			set
			{
				this._factax = value;
			}
		}
		
		private string _facemail;
		public virtual string facemail
		{
			get
			{
				return this._facemail;
			}
			set
			{
				this._facemail = value;
			}
		}
		
		private string _factel;
		public virtual string factel
		{
			get
			{
				return this._factel;
			}
			set
			{
				this._factel = value;
			}
		}
		
		private string _faccel;
		public virtual string faccel
		{
			get
			{
				return this._faccel;
			}
			set
			{
				this._faccel = value;
			}
		}
		
		private string _facfax;
		public virtual string facfax
		{
			get
			{
				return this._facfax;
			}
			set
			{
				this._facfax = value;
			}
		}
		
	}
}
#pragma warning restore 1591
