#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using WebPortal;

namespace WebPortal	
{
	public partial class Scanned
	{
		private Char _scanrectype;
		public virtual Char scanrectype
		{
			get
			{
				return this._scanrectype;
			}
			set
			{
				this._scanrectype = value;
			}
		}
		
		private string _scanrecno;
		public virtual string scanrecno
		{
			get
			{
				return this._scanrecno;
			}
			set
			{
				this._scanrecno = value;
			}
		}
		
		private string _scanrecsufx;
		public virtual string scanrecsufx
		{
			get
			{
				return this._scanrecsufx;
			}
			set
			{
				this._scanrecsufx = value;
			}
		}
		
		private string _scangroupcode;
		public virtual string scangroupcode
		{
			get
			{
				return this._scangroupcode;
			}
			set
			{
				this._scangroupcode = value;
			}
		}
		
		private string _scanfilename;
		public virtual string scanfilename
		{
			get
			{
				return this._scanfilename;
			}
			set
			{
				this._scanfilename = value;
			}
		}
		
		private string _scanpath;
		public virtual string scanpath
		{
			get
			{
				return this._scanpath;
			}
			set
			{
				this._scanpath = value;
			}
		}
		
		private DateTime? _scancreateddate;
		public virtual DateTime? scancreateddate
		{
			get
			{
				return this._scancreateddate;
			}
			set
			{
				this._scancreateddate = value;
			}
		}
		
		private DateTime? _scanupdateddate;
		public virtual DateTime? scanupdateddate
		{
			get
			{
				return this._scanupdateddate;
			}
			set
			{
				this._scanupdateddate = value;
			}
		}
		
		private string _scanuserid;
		public virtual string scanuserid
		{
			get
			{
				return this._scanuserid;
			}
			set
			{
				this._scanuserid = value;
			}
		}
		
		private string _scannotes;
		public virtual string scannotes
		{
			get
			{
				return this._scannotes;
			}
			set
			{
				this._scannotes = value;
			}
		}
		
		private string _scanorderid;
		public virtual string scanorderid
		{
			get
			{
				return this._scanorderid;
			}
			set
			{
				this._scanorderid = value;
			}
		}
		
		private string _scanstatus;
		public virtual string scanstatus
		{
			get
			{
				return this._scanstatus;
			}
			set
			{
				this._scanstatus = value;
			}
		}
		
		private string _scanmodality;
		public virtual string scanmodality
		{
			get
			{
				return this._scanmodality;
			}
			set
			{
				this._scanmodality = value;
			}
		}
		
		private string _scanloc;
		public virtual string scanloc
		{
			get
			{
				return this._scanloc;
			}
			set
			{
				this._scanloc = value;
			}
		}
		
		private string _scanmoduserid;
		public virtual string scanmoduserid
		{
			get
			{
				return this._scanmoduserid;
			}
			set
			{
				this._scanmoduserid = value;
			}
		}
		
		private System.Nullable<System.Char> _scansign;
		public virtual System.Nullable<System.Char> scansign
		{
			get
			{
				return this._scansign;
			}
			set
			{
				this._scansign = value;
			}
		}
		
		private DateTime? _scansigndate;
		public virtual DateTime? scansigndate
		{
			get
			{
				return this._scansigndate;
			}
			set
			{
				this._scansigndate = value;
			}
		}
		
		private string _scansignuser;
		public virtual string scansignuser
		{
			get
			{
				return this._scansignuser;
			}
			set
			{
				this._scansignuser = value;
			}
		}
		
		private int? _scandepts;
		public virtual int? scandepts
		{
			get
			{
				return this._scandepts;
			}
			set
			{
				this._scandepts = value;
			}
		}
		
		private string _scanpacskey;
		public virtual string scanpacskey
		{
			get
			{
				return this._scanpacskey;
			}
			set
			{
				this._scanpacskey = value;
			}
		}
		
		private string _scanstudyuid;
		public virtual string scanstudyuid
		{
			get
			{
				return this._scanstudyuid;
			}
			set
			{
				this._scanstudyuid = value;
			}
		}
		
		private string _scantransuser;
		public virtual string scantransuser
		{
			get
			{
				return this._scantransuser;
			}
			set
			{
				this._scantransuser = value;
			}
		}
		
		private DateTime? _scantransdate;
		public virtual DateTime? scantransdate
		{
			get
			{
				return this._scantransdate;
			}
			set
			{
				this._scantransdate = value;
			}
		}
		
		private System.Nullable<System.Char> _scanlock;
		public virtual System.Nullable<System.Char> scanlock
		{
			get
			{
				return this._scanlock;
			}
			set
			{
				this._scanlock = value;
			}
		}
		
		private string _scantransfile;
		public virtual string scantransfile
		{
			get
			{
				return this._scantransfile;
			}
			set
			{
				this._scantransfile = value;
			}
		}
		
		private string _scantranspath;
		public virtual string scantranspath
		{
			get
			{
				return this._scantranspath;
			}
			set
			{
				this._scantranspath = value;
			}
		}
		
		private System.Nullable<System.Char> _scandicom;
		public virtual System.Nullable<System.Char> scandicom
		{
			get
			{
				return this._scandicom;
			}
			set
			{
				this._scandicom = value;
			}
		}
		
		private string _scandictateuser;
		public virtual string scandictateuser
		{
			get
			{
				return this._scandictateuser;
			}
			set
			{
				this._scandictateuser = value;
			}
		}
		
		private DateTime? _scandictatedate;
		public virtual DateTime? scandictatedate
		{
			get
			{
				return this._scandictatedate;
			}
			set
			{
				this._scandictatedate = value;
			}
		}
		
		private string _scanreport;
		public virtual string scanreport
		{
			get
			{
				return this._scanreport;
			}
			set
			{
				this._scanreport = value;
			}
		}
		
		private string _scanreportaccno;
		public virtual string scanreportaccno
		{
			get
			{
				return this._scanreportaccno;
			}
			set
			{
				this._scanreportaccno = value;
			}
		}
		
		private string _scanvar01;
		public virtual string scanvar01
		{
			get
			{
				return this._scanvar01;
			}
			set
			{
				this._scanvar01 = value;
			}
		}
		
		private string _scanvar02;
		public virtual string scanvar02
		{
			get
			{
				return this._scanvar02;
			}
			set
			{
				this._scanvar02 = value;
			}
		}
		
		private ScanGroup _scangroup;
		public virtual ScanGroup scangroup
		{
			get
			{
				return this._scangroup;
			}
			set
			{
				this._scangroup = value;
			}
		}
		
	}
}
#pragma warning restore 1591
