#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using WebPortal;

namespace WebPortal	
{
	public partial class ScanGroup
	{
		private string _groupcode;
		public virtual string groupcode
		{
			get
			{
				return this._groupcode;
			}
			set
			{
				this._groupcode = value;
			}
		}
		
		private string _groupdescription;
		public virtual string groupdescription
		{
			get
			{
				return this._groupdescription;
			}
			set
			{
				this._groupdescription = value;
			}
		}
		
		private string _grouppath;
		public virtual string grouppath
		{
			get
			{
				return this._grouppath;
			}
			set
			{
				this._grouppath = value;
			}
		}
		
		private System.Nullable<System.Char> _groupsign;
		public virtual System.Nullable<System.Char> groupsign
		{
			get
			{
				return this._groupsign;
			}
			set
			{
				this._groupsign = value;
			}
		}
		
		private System.Nullable<System.Char> _groupdocworklist;
		public virtual System.Nullable<System.Char> groupdocworklist
		{
			get
			{
				return this._groupdocworklist;
			}
			set
			{
				this._groupdocworklist = value;
			}
		}
		
		private IList<Scanned> _scanneds = new List<Scanned>();
		public virtual IList<Scanned> Scanneds
		{
			get
			{
				return this._scanneds;
			}
		}
		
	}
}
#pragma warning restore 1591
